

GET http://localhost:3001/api/noEnqueued/1 HTTP/1.1

###

GET http://localhost:3001/api/noServed/1 HTTP/1.1

###
GET http://localhost:3001/api/services HTTP/1.1

###
GET http://localhost:3001/api/counters HTTP/1.1

###
GET http://localhost:3001/api/counters/2 HTTP/1.1

###
GET http://localhost:3001/api/counters/1/tickets HTTP/1.1
###
GET http://localhost:3001/api/counters/available HTTP/1.1

###
POST http://localhost:3001/api/tickets/print/1 HTTP/1.1

###
GET http://localhost:3001/api/tickets/getAllTickets HTTP/1.1

###
GET http://localhost:3001/api/tickets/1  HTTP/1.1

###
GET http://localhost:3001/api/services/1/services  HTTP/1.1

